# cargo run -- init -m -r origin/main -t 'cargo clippy' -t 'cargo fmt' -t mdlynx -t shellcheck -t ttlint -t typos -t zizmor

refs = ["origin/main"]

[[linter]]
name = "cargo clippy"
cmd = "cargo clippy --color=always --all-targets -- --deny warnings"
files = ["*.rs"]
granularity = "batch"
configs = ["Cargo.toml"]
fix = "cargo clippy --color=always --allow-dirty --fix"

[[formatter]]
name = "cargo fmt"
cmd = "cargo fmt --"
files = ["*.rs"]
granularity = "batch"
configs = ["Cargo.toml"]

[[linter]]
name = "mdlynx"
cmd = "mdlynx --"
files = ["*.md"]

[[linter]]
name = "shellcheck"
cmd = "shellcheck --color=always --"
files = ["*.sh"]

[[linter]]
name = "ttlint"
cmd = "ttlint --"
files = ["*"]
fix = "ttlint --fix --"

[[linter]]
name = "typos"
cmd = "typos --"
files = ["*.md"]
fix = "typos --write-changes --"

[[linter]]
name = "zizmor"
cmd = "zizmor --"
files = [".github/**/*.yml"]
fix = "zizmor --fix=safe --"
ignore = [".github/**/dependabot.yml"]
