# cargo run -- init -m -r origin/main -t 'cargo clippy' -t 'cargo fmt' -t mdlynx -t shellcheck -t ttlint -t typos

mtime = true
refs = ["origin/main"]

[[tool]]
name = "cargo clippy"
cmd = "cargo clippy --color=always --all-targets -- --deny warnings"
files = "*.rs"
granularity = "batch"
configs = ["Cargo.toml"]
fix = "cargo clippy --color=always --allow-dirty --fix"

[[tool]]
name = "cargo fmt"
cmd = "cargo fmt --"
files = "*.rs"
granularity = "batch"
configs = ["Cargo.toml"]
check = "cargo fmt --check"
formatter = true

[[tool]]
name = "mdlynx"
cmd = "mdlynx --"
files = "*.md"

[[tool]]
name = "shellcheck"
cmd = "shellcheck --color=always --"
files = "*.sh"

[[tool]]
name = "ttlint"
cmd = "ttlint --"
files = "*"
fix = "ttlint --fix --"

[[tool]]
name = "typos"
cmd = "typos --"
files = "*.md"
fix = "typos --write-changes --"
